"use client";
import { DarkThemeToggle, Flowbite, ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { useTranslation } from "react-i18next";
import { useEffect } from "react";
import "../config/i18next";
import StoreProvider from "./StoreProvider";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "OMR License Plate",
//   //   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html>
        <head>
          <ThemeModeScript />
        </head>
        <body className="dark:bg-slate-900 bg-gray-200">
          {" "}
          <Flowbite>
            {children}

            {/* <DarkThemeToggle /> */}

            <Toaster />
          </Flowbite>
        </body>
      </html>
    </StoreProvider>
  );
}
